### ISSUE TITLE
Tooltips need more time threshold

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui-style-guide#11]
@froooze commented on [Wed Jun 19 2019](https://github.com/bitshares/bitshares-ui/issues/2809)

**Describe the bug**
Tooltip pop now up, when I move over by accident with mouse and this is annoying. 

**To Reproduce**
1. Go to Exchange/Dashboard
2. move over a tooltip 

**Expected behavior**
Time threshold of 500ms

**Desktop (please complete the following information):**
 - OS: MX-Linux, Light client

---

@startailcoon commented on [Sat Jun 22 2019](https://github.com/bitshares/bitshares-ui/issues/2809#issuecomment-504696558)

It is indeed quick, and I've reacted the same. Component is this https://ant.design/components/tooltip. 

@gibbsfromncis can we change this behavior?

---

@gibbsfromncis commented on [Mon Jul 15 2019](https://github.com/bitshares/bitshares-ui/issues/2809#issuecomment-511481815)

@startailcoon I'm not sure how can we change the default behavior but I guess we can change it for separate tooltips. ant component https://ant.design/components/tooltip/ is based on https://github.com/react-component/tooltip. So you can use this prop `mouseEnterDelay` to define delay before show tooltip

---

@froooze commented on [Tue Jul 16 2019](https://github.com/bitshares/bitshares-ui/issues/2809#issuecomment-511586766)

@gibbsfromncis: There is no global setting for time threshold ?

---

@sschiessl-bcp commented on [Tue Jul 16 2019](https://github.com/bitshares/bitshares-ui/issues/2809#issuecomment-511749022)

> @gibbsfromncis: There is no global setting for time threshold ?

The global setting would be what we add as default in the style-guide. Currently the default is 0.

---

@react-cat commented on [Mon Jul 22 2019](https://github.com/bitshares/bitshares-ui/issues/2809#issuecomment-513959269)

@sschiessl-bcp as a solution we can create a HOC for ant tooltip. So behavior will be the next. That HOC would simply pass down all props to ant tooltip and add mouseEnterDelay with delay of 0.5ms in case if that prop wasn't already passed. 
Pros: we will set a default dealy to all tooltips. 
Cons: we would have change tooltip imports all over the project and import our tooltip except ant's tooltip in future

---

@sschiessl-bcp commented on [Fri Aug 02 2019](https://github.com/bitshares/bitshares-ui/issues/2809#issuecomment-517684824)

That's exactly what we have bitshares-style-guide repo for, please adjust there.

**Comment by startailcoon** [comment]
Tooltip should handle `onMouseDelay` if passed, and default to 0.5s.

**Comment by react-cat** [comment]
@startailcoon It would be better to correspond default Ants props. Ants tooltip doesn't have any `onMouseDelay`, it have `mouseEnterDelay` and `mouseLeaveDelay` so due to this it would be better to use `mouseEnterDelay` instead of `onMouseDelay`. This way we just change the default behavior and anyone who use Tooltips can just follow official docs.

**Comment by startailcoon** [comment]
Since this is what the ANT docs uses, I'd agree with using the standard names. Please go ahead and implement this as you've suggested, sounds good to me.
