### ISSUE TITLE
npm run start fails

### ISSUE THREAD

**Issue by GBKS** [bitshares/bitshares-ui-style-guide#2]
I wanted to get a feel for the UI design and check out this style guide, but can't get it to work. Below is the output from the log file. I have no idea what to make of it, any tips are appreciated. 

`0 info it worked if it ends with ok
1 verbose cli [ '/Users/christoph/.nvm/versions/node/v6.11.3/bin/node',
1 verbose cli   '/Users/christoph/.nvm/versions/node/v6.11.3/bin/npm',
1 verbose cli   'run',
1 verbose cli   'theme-watch:midnight' ]
2 info using npm@6.2.0
3 info using node@v6.11.3
4 verbose run-script [ 'pretheme-watch:midnight',
4 verbose run-script   'theme-watch:midnight',
4 verbose run-script   'posttheme-watch:midnight' ]
5 info lifecycle bitshares-ui-style-guide@1.0.0~pretheme-watch:midnight: bitshares-ui-style-guide@1.0.0
6 info lifecycle bitshares-ui-style-guide@1.0.0~theme-watch:midnight: bitshares-ui-style-guide@1.0.0
7 verbose lifecycle bitshares-ui-style-guide@1.0.0~theme-watch:midnight: unsafe-perm in lifecycle true
8 verbose lifecycle bitshares-ui-style-guide@1.0.0~theme-watch:midnight: PATH: /Users/christoph/.nvm/versions/node/v6.11.3/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/christoph/workspace/bitshares-ui-style-guide/node_modules/.bin:/Users/christoph/.nvm/versions/node/v6.11.3/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/christoph/workspace/bitshares-ui-style-guide/node_modules/.bin:/Users/christoph/.nvm/versions/node/v6.11.3/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/christoph/workspace/bitshares-ui-style-guide/node_modules/.bin:/Users/christoph/.nvm/versions/node/v6.11.3/bin:/Users/christoph/.rbenv/bin:/Users/christoph/.rbenv/shims:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle bitshares-ui-style-guide@1.0.0~theme-watch:midnight: CWD: /Users/christoph/workspace/bitshares-ui-style-guide
10 silly lifecycle bitshares-ui-style-guide@1.0.0~theme-watch:midnight: Args: [ '-c',
10 silly lifecycle   './node_modules/less-watch-cli/index.js app/bitshares-ui-style-guide/styles/midnight/midnight-theme.less app/bitshares-ui-style-guide/styles/midnight/midnight-theme.css' ]
11 silly lifecycle bitshares-ui-style-guide@1.0.0~theme-watch:midnight: Returned: code: 1  signal: null
12 info lifecycle bitshares-ui-style-guide@1.0.0~theme-watch:midnight: Failed to exec theme-watch:midnight script
13 verbose stack Error: bitshares-ui-style-guide@1.0.0 theme-watch:midnight: `./node_modules/less-watch-cli/index.js app/bitshares-ui-style-guide/styles/midnight/midnight-theme.less app/bitshares-ui-style-guide/styles/midnight/midnight-theme.css`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/christoph/.nvm/versions/node/v6.11.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (/Users/christoph/.nvm/versions/node/v6.11.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:920:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
14 verbose pkgid bitshares-ui-style-guide@1.0.0
15 verbose cwd /Users/christoph/workspace/bitshares-ui-style-guide
16 verbose Darwin 17.7.0
17 verbose argv "/Users/christoph/.nvm/versions/node/v6.11.3/bin/node" "/Users/christoph/.nvm/versions/node/v6.11.3/bin/npm" "run" "theme-watch:midnight"
18 verbose node v6.11.3
19 verbose npm  v6.2.0
20 error code ELIFECYCLE
21 error errno 1
22 error bitshares-ui-style-guide@1.0.0 theme-watch:midnight: `./node_modules/less-watch-cli/index.js app/bitshares-ui-style-guide/styles/midnight/midnight-theme.less app/bitshares-ui-style-guide/styles/midnight/midnight-theme.css`
22 error Exit status 1
23 error Failed at the bitshares-ui-style-guide@1.0.0 theme-watch:midnight script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Comment by gibbsfromncis** [comment]
I have no idea what is going on there. I'll close it and if you still have an interest to solve your issue please reopen it.

**Comment by svk31** [comment]
Probably from using an old version of Node (v6), try upgrading to v9 or 10

**Comment by GBKS** [comment]
Thank you, it was due to an old version of node.
