### ISSUE TITLE
Update and resolve vulnerabilities

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui-style-guide#9]
`npm install` should show no vulnerabilities.

@gibbsfromncis ?

**Comment by react-cat** [comment]
@sschiessl-bcp Can I claim that ? 
I found that currently we have 614 dangerous vulnerabilities and 78 less critical
![image](https://user-images.githubusercontent.com/43940398/62807456-10555c80-bafe-11e9-8907-d4face25d380.png)

Currently it's hard to say how many time I need to solve it, cause some vulnerabilities could be simple to fix by automatic methods and some may don't

**Comment by sschiessl-bcp** [comment]
Yes please do. 

While you are at it, please update antd to latest version, and double check the style guide that the raw component still work as expected (deployed under https://styleguide.bitshares.org/#/, see package.json how to start that locally)

If you realize it's gonna take more than 3 hours, please ping us.

**Comment by sschiessl-bcp** [comment]
includes #6

**Comment by sschiessl-bcp** [comment]
Resolved by @gibbsfromncis
